name: flutter_html
description: A Flutter widget rendering static HTML and CSS as Flutter widgets.
version: 2.1.5
homepage: https://github.com/Sub6Resources/flutter_html

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.2.0'

dependencies:
  flutter:
    sdk: flutter
  # Plugin for parsing html
  html: ^0.15.0
  # Plugins for parsing css
  csslib: ^0.17.1
  # Plugins for rendering the <table> tag.
  flutter_layout_grid: ^1.0.3

  # Plugins for rendering the <video> tag.
  video_player: ^2.2.4
  chewie: ^1.3.0

  # Plugin for rendering the <iframe> tag.
  webview_flutter: ^3.0.0

  # Plugins for rendering the <audio> tag.
  chewie_audio: ^1.3.0

  # Plugins for rendering the <svg> tag.
  flutter_svg: ^1.0.3

  # Plugin for rendering MathML
  flutter_math_fork: ^0.6.1

  # plugin for firstWhereOrNull extension on lists
  collection: ^1.15.0

  # plugin to convert integers to numerals
  numerus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
